### ISSUE TITLE
Can I use ws2812b ? 

### ISSUE THREAD

**Issue by minsuke** [rnauber/ESPHomeMatrixLED#2]
This is great project I want to do 

I have one question, Can I use ws2812b same code ? 

I am very appreciate to you share project : )

**Comment by rnauber** [comment]
If it is supported by esphome, you can use it:
https://esphome.io/components/light/fastled.html

Just change this line accordingly:

https://github.com/rnauber/ESPHomeMatrixLED/blob/1e5e4315d6f7648e510c25a2da1002dbabcfef57/matrixleddemo.yaml#L40

Please report back, if it did work as expected.
Have fun,
Richard

**Comment by rnauber** [comment]
I guess, it should work, so am closing this issue. Feel free to reopen, if it does not...
