### ISSUE TITLE
Scrolling text

### ISSUE THREAD

**Issue by tube0013** [rnauber/ESPHomeMatrixLED#6]
Any pointers on having a text string scroll like the clock does?

**Comment by rnauber** [comment]
You can easily modify the example to do that. Here a quick hack to get started:

Set your text here, replacing "%M %H:%M %H":

https://github.com/rnauber/ESPHomeMatrixLED/blob/1ae4f283dc22889b0f48b4ff47a242139b3a294b/matrixleddemo.yaml#L182


And update the maximum length of the string here, replacing the 16:
https://github.com/rnauber/ESPHomeMatrixLED/blob/1ae4f283dc22889b0f48b4ff47a242139b3a294b/matrixleddemo.yaml#L161

**Comment by tube0013** [comment]
thank you for this.  I got it to work, partly, I have a string of 24 characters, and I updated both locations however only the middle 8 characters display.

**Comment by rnauber** [comment]
Oh, you should also replace the "6" here:

https://github.com/rnauber/ESPHomeMatrixLED/blob/1ae4f283dc22889b0f48b4ff47a242139b3a294b/matrixleddemo.yaml#L186

Sorry, this is all a big hack. For my current projects I created a class that allows to scroll a small viewport over a large area. I will publish it here, if I will find the time (not to soon)...

**Comment by apolselli** [comment]
Hi, you can try my example m5atom_marquee.yaml that does exactly this, a scrolling text on a 5x5 display:
https://github.com/rnauber/ESPHomeMatrixLED/blob/master/m5atom_marquee.yaml

**Comment by tube0013** [comment]
Thank you both!  I got the first method to work but it had quite a delay between starting the text again. Modified the m5atom_marquee to use a template_text sensor for my text string and working well.  Sticking a 8x32 matrix in a car window for end of school drive-by-parade for my kids today.  Thanks again!

**Comment by rnauber** [comment]
Great! I am sure your kids will enjoy this!
